on:
  push:
    branches:
      - adaptors-version-upgrade

concurrency:
  group: openfn-deployment
  cancel-in-progress: false

jobs:
  deploy-to-lightning:
    runs-on: ubuntu-latest
    name: A job to deploy to Lightning
    permissions:
      contents: write
    steps:
      - name: openfn deploy
        uses: openfn/cli-deploy-action@v1.0.0
        with:
          secret_input: ${{ secrets.OPENFN_82782579_ba3c_4837_9f0e_d36901efe33b_API_KEY }}
          config_path_input: 'openfn-82782579-ba3c-4837-9f0e-d36901efe33b-config.json'
